on:
  workflow_call:
    inputs:
      ref:
        required: false
        type: string
        default: ''
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - name: Build docker image
        run: docker compose build app
