on:
  workflow_call:
    inputs:
      ref:
        required: false
        type: string
        default: ''
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler: "default"
      - name: Install dependencies
        run: bundle install
      - name: Run linter
        run: bundle exec rake rubocop
