name: CI

on:
  push:
    branches:
      - main
      - "release-*"
  pull_request:
jobs:
  lint:
    uses: maxkadel/actions/.github/workflows/lint.yml@main
  test:
    uses: maxkadel/actions/.github/workflows/test.yml@main
  docker_build:
    uses: maxkadel/actions/.github/workflows/build.yml@main
