name: CI

on:
  push:
    branches:
      - main
      - "release-*"
  pull_request:
jobs:
  # lint:
  #   uses: maxkadel/actions/.github/workflows/lint.yml@main
  test:
    uses: maxkadel/actions/.github/workflows/test.yml@main
    with:
      ruby: '["3.4"]'
  # docker_build:
  #   uses: maxkadel/actions/.github/workflows/build.yml@main
