# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: CI

on:
  push:
    branches:
      - main
      - 'release-*'
  pull_request:

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  test_rails7_1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [3.2, 3.3]
    env:
      RAILS_VERSION: 7.1.5.1
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler: 'default'
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rake ci
      env:
        ENGINE_CART_RAILS_OPTIONS: '--skip-git --skip-listen --skip-spring --skip-keeps --skip-coffee --skip-test'
  test_bootstrap5:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [3.3]
    env:
      RAILS_VERSION: 7.1.5.1
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler: 'default'
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rake ci
      env:
        BOOTSTRAP_VERSION: '~> 5.0'
        ENGINE_CART_RAILS_OPTIONS: '--skip-git --skip-listen --skip-spring --skip-keeps --skip-coffee --skip-test'
  test_rails7_2:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [3.3, 3.4]
    env:
      RAILS_VERSION: 7.2.2.1
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler: 'default'
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rake ci
      env:
        ENGINE_CART_RAILS_OPTIONS: '--skip-keeps --skip-test'
  test_vc2:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [3.3]
    env:
      RAILS_VERSION: 7.1.5.1
      VIEW_COMPONENT_VERSION: "~> 2.74"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler: 'default'
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rake ci
      env:
        ENGINE_CART_RAILS_OPTIONS: '--skip-git --skip-listen --skip-spring --skip-keeps --skip-coffee --skip-test'
  api_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [3.2, 3.3]
    env:
      RAILS_VERSION: 7.1.5.1
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler: 'default'
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rake ci
      env:
        BLACKLIGHT_API_TEST: true
        ENGINE_CART_RAILS_OPTIONS: '-a propshaft --api --skip-git --skip-bundle --skip-listen --skip-spring --skip-yarn --skip-keeps --skip-action-cable --skip-coffee --skip-test'
  docker_build:
    uses: ./.github/workflows/build.yml
